# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 00:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bineta', '0024_remove_correction_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_monthly', models.BooleanField(default=True, verbose_name=b'monthly')),
                ('is_annual', models.BooleanField(default=False, verbose_name=b'annual')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'creation_date')),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'modification_date')),
            ],
            options={
                'db_table': 'Subscription',
            },
        ),
        migrations.CreateModel(
            name='USerSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'creation_date')),
                ('begin_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'begin_date')),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type', models.CharField(max_length=100)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='USerSubscription', to='Bineta.Subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='USerSubscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='is_annual',
            field=models.BooleanField(default=False, verbose_name=b'annual'),
        ),
        migrations.AddField(
            model_name='school',
            name='is_monthly',
            field=models.BooleanField(default=True, verbose_name=b'monthly'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subs', through='Bineta.USerSubscription', to='Bineta.Subscription'),
        ),
    ]
