# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bineta', '0025_auto_20160414_0202'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersubscription',
            table='USerSubscription',
        ),
    ]
