# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bineta', '0026_auto_20160414_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='deletion_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name=b'deletion_date'),
        ),
    ]
