# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bineta', '0027_subscription_deletion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nb_points',
        ),
    ]
