# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bineta', '0028_remove_user_nb_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='is_annual',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_monthly',
        ),
    ]
