# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 00:08
from __future__ import unicode_literals

import Bineta.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bineta', '0029_auto_20160415_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(b'U', 'unknown'), (b'M', 'male'), (b'F', 'female')], default=b'U', max_length=1, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=Bineta.models.upload_thumbnail),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bineta.School'),
        ),
    ]
