# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 20:47
from __future__ import unicode_literals

import Bineta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bineta', '0030_auto_20160417_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='mock_exam',
        ),
        migrations.AddField(
            model_name='document',
            name='document_thumbnail',
            field=models.ImageField(default=None, upload_to=Bineta.models.upload_document_thumbnail),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[(b'R', 'real'), (b'M', 'mock'), (b'C', 'common')], default=b'R', max_length=1, verbose_name='exam_type'),
        ),
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
